### ISSUE TITLE
oscillation

### ISSUE THREAD

**Issue by nomyTx** [nitin-ojha1/nitin-ojha1#2]
oscillate some bitches

**Comment by kekkodance** [comment]
you need to oscillate some bithces @nitin-ojha1

**Comment by nitin-ojha1** [comment]
![Screenshot_2021-09-07-20-23-22-422_com.android.chrome.jpg](https://user-images.githubusercontent.com/81779298/132366081-3b06c961-8092-4aa1-a031-bcdf97ec61f1.jpg)

uhh what? i dont understand

**Comment by nitin-ojha1** [comment]
i thought the argument was closed a day ago when you all people banned me
